keywordTexts = {
	"deathtouch": "Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.)",
	"defender": "Defender (This creature can’t attack.)",
	"double strike": "Double strike (This creature deals both first‑strike and regular combat damage.)",
	"enchant": "Enchant — [the enchanted permanent type] (This Aura enters the battlefield attached to that permanent.)",
	"equip": "Equip [cost] (Attach this to target creature you control. Activate only as a sorcery.)",
	"first strike": "First strike (This creature deals combat damage before creatures without first strike.)",
	"flash": "Flash (You may cast this spell any time you could cast an instant.)",
	"flying": "Flying (This creature can only be blocked by creatures with flying or reach.)",
	"haste": "Haste (This creature can attack and {T} as soon as it comes under your control.)",
	"hexproof": "Hexproof (This permanent can’t be the target of spells or abilities your opponents control.)",
	"indestructible": "Indestructible (Effects that say “destroy” don’t destroy this.)",
	"lifelink": "Lifelink (Damage dealt by this creature also causes you to gain that much life.)",
	"menace": "Menace (This creature can’t be blocked except by two or more creatures.)",
	"reach": "Reach (This creature can block creatures with flying.)",
	"shroud": "Shroud (This permanent can’t be the target of any spells or abilities.)",
	"trample": "Trample (This creature can deal excess combat damage to the player or planeswalker it’s attacking.)",
	"vigilance": "Vigilance (Attacking doesn’t cause this creature to tap.)",
	"cascade": "Cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card with lesser mana value. You may cast that card without paying its mana cost.)",
	"madness": "Madness [cost] (If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.)",
	"ninjutsu": "Ninjutsu [cost] ([cost], Return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.)",
	"escape": "Escape [cost] (You may cast this card from your graveyard for its escape cost by exiling other cards from your graveyard.)",
	"embalm": "Embalm [cost] ([Cost], Exile this card from your graveyard: Create a token that’s a copy of it, except it’s a white Zombie with no mana cost. Embalm only as a sorcery.)",
	"eternalize": "Eternalize [cost] ([Cost], Exile this card from your graveyard: Create a 4/4 black Zombie token with no mana cost. Eternalize only as a sorcery.)",
	"mutate": "Mutate [cost] (If you cast this spell for its mutate cost, put it over or under target non-Human creature you own. They mutate into the creature on top plus all abilities from under it.)",
	"modular": "Modular N (This creature enters the battlefield with N +1/+1 counters on it. When it dies, you may put its +1/+1 counters on target artifact creature.)",
	"persist": "Persist (When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner’s control with a -1/-1 counter on it.)",
	"undying": "Undying (When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner’s control with a +1/+1 counter on it.)",
	"aftermath": "Aftermath (Cast this spell only from your graveyard. Then exile it.)",
	"suspend": "Suspend N—[cost] (Rather than cast this card from your hand, pay [cost] and exile it with N time counters. At the beginning of your upkeep, remove a counter. When the last is removed, cast it without paying its mana cost.)",
	"foretell": "Foretell [cost] (During your turn, you may pay {2} and exile this card from your hand face down. Cast it later for its foretell cost.)",
	"bestow": "Bestow [cost] (If you cast this card for its bestow cost, it’s an Aura spell with enchant creature. If it’s not attached to a creature, it becomes a creature again.)",
	"awaken": "Awaken N—[cost] (If you cast this spell for [cost], also put N +1/+1 counters on target land you control and it becomes a 0/0 Elemental creature with haste.)",
	"dash": "Dash [cost] (You may cast this spell for its dash cost. If you do, it gains haste, and return it from the battlefield to its owner’s hand at the beginning of the next end step.)",
	"riot": "Riot (This creature enters the battlefield with your choice of a +1/+1 counter or haste.)",
	"mentor": "Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)",
	"protection": "Protection from [quality] (This can’t be damaged, enchanted, equipped, blocked or targeted by anything [quality].)",
	"ward": "Ward [cost] (Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays [cost].)",
	"flashback": "Flashback [cost] (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
	"cycling": "Cycling [cost] ([Cost], Discard this card: Draw a card.)",
	"buyback": "Buyback [cost] (You may pay an additional [cost] as you cast this spell. If you do, put it into your hand instead of your graveyard as it resolves.)",
	"kicker": "Kicker [cost] (You may pay an additional [cost] as you cast this spell.)",
	"convoke": "Convoke (Your creatures can help cast this spell. Each creature you tap while casting this spell pays for {1} or one mana of that creature’s color.)",
	"affinity": "Affinity for [type] (This spell costs {1} less to cast for each [type] you control.)",
	"prowl": "Prowl [cost] (You may cast this for its prowl cost if you dealt combat damage to a player with a [subtype] this turn.)",
	"spectacle": "Spectacle [cost] (You may cast this spell for its spectacle cost rather than its mana cost if an opponent lost life this turn.)",
	"evoke": "Evoke [cost] (You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters the battlefield.)",
	"split second": "Split second (As long as this spell is on the stack, players can’t cast spells or activate abilities that aren’t mana abilities.)",
	"unleash": "Unleash (You may have this creature enter the battlefield with a +1/+1 counter. It can’t block as long as it has a +1/+1 counter on it.)",
	"overload": "Overload [cost] (You may cast this spell for its overload cost. If you do, change its text by replacing all instances of “target” with “each.”)",
	"scavenge": "Scavenge [cost] ([Cost], Exile this card from your graveyard: Put a number of +1/+1 counters equal to this card’s power on target creature. Scavenge only as a sorcery.)",
	"soulbond": "Soulbond (You may pair this creature with another unpaired creature when either enters the battlefield. They remain paired as long as you control both.)",
	"morph": "Morph [cost] (You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.)",
	"megamorph": "Megamorph [cost] (You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its megamorph cost with a +1/+1 counter.)",
	"exploit": "Exploit (When this creature enters the battlefield, you may sacrifice a creature.)",
	"intimidate": "Intimidate (This creature can’t be blocked except by artifact creatures and/or creatures that share a color with it.)",
	"extort": "Extort (Whenever you cast a spell, you may pay {W/B}. If you do, each opponent loses 1 life and you gain that much life.)",
	"vanishing": "Vanishing N (This permanent enters with N time counters. At the beginning of your upkeep, remove one. Sacrifice it when the last is removed.)",
	"fading": "Fading N (This permanent enters with N fade counters. Remove one at the beginning of your upkeep. Sacrifice it when the last is removed.)",
	"storm": "Storm (When you cast this spell, copy it for each other spell cast this turn. You may choose new targets for the copies.)",
	"myriad": "Myriad (When this creature attacks, for each opponent other than defending player, create a copy that’s tapped and attacking that opponent or a planeswalker they control. Exile the copies at end of combat.)",
	"renown": "Renown N (When this creature deals combat damage to a player, if it isn’t renowned, put N +1/+1 counters on it and it becomes renowned.)",
	"prowess": "Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)",
	"tribal": "Tribal (A card type that exists only on spells and not on permanents.)",
	"changeling": "Changeling (This card is every creature type.)",
	"outlast": "Outlast [cost] ([Cost]: Put a +1/+1 counter on this creature. Activate only as a sorcery.)",
	"rebound": "Rebound (If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, you may cast it without paying its mana cost.)",
	"miracle": "Miracle [cost] (You may cast this card for its miracle cost when you draw it if it’s the first card you drew this turn.)",
	"transmute": "Transmute [cost] ([Cost], Discard this card: Search your library for a card with the same mana value, reveal it, put it into your hand, then shuffle. Transmute only as a sorcery.)",
	"graft": "Graft N (This creature enters the battlefield with N +1/+1 counters on it. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this creature onto it.)",
	"forecast": "Forecast — [Cost], Reveal this card from your hand: [Effect]. Activate only during your upkeep and only once each turn.",
	"replicate": "Replicate [cost] (When you cast this spell, copy it for each time you paid its replicate cost. You may choose new targets for the copies.)",
	"recover": "Recover [cost] (When a creature is put into your graveyard from the battlefield, you may pay [cost]. If you do, return this card from your graveyard to your hand. Otherwise, exile this card.)",
	"soulshift": "Soulshift N (When this creature dies, you may return target Spirit card with mana value N or less from your graveyard to your hand.)",
	"level up": "Level up [cost] ([Cost]: Put a level counter on this. Level up only as a sorcery.)",
	"totem armor": "Totem armor (If enchanted permanent would be destroyed, instead remove all damage from it and destroy this Aura.)",
	"phasing": "Phasing (This permanent phases in or out during its controller’s untap step. It is treated as though it doesn’t exist while phased out.)",
	"transfigure": "Transfigure [cost] ([Cost], Sacrifice this creature: Search your library for a creature card with the same mana value, put it onto the battlefield, then shuffle. Transfigure only as a sorcery.)",
	"poisonous": "Poisonous N (Whenever this creature deals combat damage to a player, that player gets N poison counters.)",
	"wither": "Wither (This deals damage to creatures in the form of -1/-1 counters.)",
	"infect": "Infect (This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.)",
	"bushido": "Bushido N (When this blocks or becomes blocked, it gets +N/+N until end of turn.)",
	"rampage": "Rampage N (Whenever this creature becomes blocked, it gets +N/+N until end of turn for each creature blocking it beyond the first.)",
	"flanking": "Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)",
	"horsemanship": "Horsemanship (This creature can’t be blocked except by creatures with horsemanship.)",
	"shadow": "Shadow (This creature can block or be blocked only by creatures with shadow.)",
	"amplify": "Amplify N (As this creature enters the battlefield, reveal any number of cards in your hand that share a creature type with it. This creature enters the battlefield with N +1/+1 counters for each card revealed this way.)",
	"banding": "Banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. You choose how combat damage is assigned.)",
	"cumulative upkeep": "Cumulative upkeep [cost] (At the beginning of your upkeep, put an age counter on this permanent. Then sacrifice it unless you pay its upkeep cost for each age counter on it.)",
	"meld": "Meld (You may meld two specific cards if you both own and control them. They form a single oversized card with combined characteristics.)",
	"crew": "Crew N (Tap any number of creatures you control with total power N or more: This Vehicle becomes an artifact creature until end of turn.)",
	"partner": "Partner (You can have two commanders if both have partner.)",
	"partner with": "Partner with [name] (When this creature enters the battlefield, target player may search their library for [name], reveal it, put it into their hand, then shuffle.)",
	"assist": "Assist (Another player can help you cast this spell. They can pay up to half of its mana cost.)",
	"devour": "Devour N (As this enters the battlefield, you may sacrifice any number of creatures. It enters the battlefield with N +1/+1 counters for each creature sacrificed.)",
	"tribute": "Tribute N (As this creature enters the battlefield, an opponent may put N +1/+1 counters on it. If they don’t, [effect].)",
	"dredge": "Dredge N (If you would draw a card, you may instead put exactly N cards from the top of your library into your graveyard. If you do, return this card from your graveyard to your hand.)",
	"delve": "Delve (Each card you exile from your graveyard while casting this spell pays for {1}.)",
	"emerge": "Emerge [cost] (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature’s mana value.)",
	"escalate": "Escalate [cost] (Pay this cost for each mode chosen beyond the first.)",
	"cipher": "Cipher (Then you may exile this spell encoded on a creature you control. Whenever that creature deals combat damage to a player, its controller may cast a copy of the encoded card without paying its mana cost.)",
	"splice": "Splice onto Arcane [cost] (As you cast an Arcane spell, you may reveal this card from your hand and pay its splice cost. If you do, add this card’s effects to that spell.)",
	"conspire": "Conspire (As you cast this spell, you may tap two untapped creatures you control that share a color with it. When you do, copy it.)",
	"entwine": "Entwine [cost] (Choose both if you pay the entwine cost.)",
	"epic": "Epic (For the rest of the game, you can’t cast spells. At the beginning of each of your upkeeps, copy this spell except for its epic ability.)",
	"hideaway": "Hideaway N (This enters the battlefield tapped. When it does, look at the top N cards of your library, exile one face down, then put the rest on the bottom. You may play the exiled card later under certain conditions.)",
	"fabricate": "Fabricate N (When this creature enters the battlefield, put N +1/+1 counters on it or create N 1/1 Servo artifact creature tokens.)",
	"craft": "Craft with [type] — [Cost] (You may exile this permanent and other permanents of the specified type to transform it. Activate only as a sorcery.)",
	"training": "Training (Whenever this creature attacks with another creature with greater power, put a +1/+1 counter on this creature.)",
	"disturb": "Disturb [cost] (You may cast this card from your graveyard transformed for its disturb cost.)",
	"decayed": "Decayed (This creature can’t block, and when it attacks, sacrifice it at end of combat.)",
	"read ahead": "Read ahead (You may start this Saga on any chapter. Skip all previous chapters when it enters the battlefield.)",
	"backup": "Backup N (When this creature enters the battlefield, put N +1/+1 counters on target creature. If it's another creature, it gains the listed abilities until end of turn.)",
	"bargain": "Bargain (You may sacrifice an artifact, enchantment, or token as you cast this spell for additional effect.)",
	"toxic": "Toxic N (Players dealt combat damage by this creature also get N poison counters.)",
	"prototype": "Prototype (You may cast this spell with different mana cost, power, and toughness. It retains its abilities and types.)",
	"reconfigure": "Reconfigure [cost] ([Cost]: Attach to target creature you control; or unattach from a creature. Reconfigure only as a sorcery.)",
	"double agenda": "Double agenda (Hidden agenda variant allowing two conspiracies to affect the same card.)",
	"hidden agenda": "Hidden agenda (Start the game with this conspiracy face down. You may turn it face up at any time to affect a named card.)",
	"friends forever": "Friends forever (You can have two commanders if both have friends forever.)",
	"absorb": "Absorb N (If a source would deal damage to this creature, prevent N of that damage.)",
	"afflict": "Afflict N (Whenever this creature becomes blocked, defending player loses N life.)",
	"afterlife": "Afterlife N (When this creature dies, create N 1/1 white and black Spirit creature tokens with flying.)",
	"annihilator": "Annihilator N (Whenever this creature attacks, defending player sacrifices N permanents.)",
	"ascend": "Ascend (If you control ten or more permanents, you get the city’s blessing for the rest of the game.)",
	"augment": "Augment [Cost] ([Cost]: Combine this creature with a host to create a new creature. Activate only as a sorcery.)",
	"aura swap": "Aura swap [Cost] ([Cost]: Exchange this Aura with an Aura card in your hand.)",
	"battle cry": "Battle cry (Whenever this creature attacks, each other attacking creature gets +1/+0 until end of turn.)",
	"blitz": "Blitz [Cost] (You may cast this spell for its blitz cost. If you do, it gains haste and “When this creature dies, draw a card.” Sacrifice it at end of turn.)",
	"bloodrush": "Bloodrush — [Cost], Discard this card: Target attacking creature gets +X/+Y and gains [ability] until end of turn.",
	"bloodthirst": "Bloodthirst N (If an opponent was dealt damage this turn, this creature enters the battlefield with N +1/+1 counters.)",
	"boast": "Boast — [Cost]: Activate only if this creature attacked this turn and only once each turn.",
	"champion": "Champion a [Type] (When this enters the battlefield, sacrifice it unless you exile another [Type] you control. When this leaves the battlefield, return that card.)",
	"cleave": "Cleave [Cost] (You may cast this spell for its cleave cost. If you do, remove the words in square brackets.)",
	"commander ninjutsu": "Commander ninjutsu [Cost] ([Cost], Return an unblocked attacker you control to hand: Put this card onto the battlefield tapped and attacking.)",
	"companion": "Companion — If your starting deck meets the stated condition, you may cast this card once from outside the game.",
	"compleated": "Compleated (This planeswalker can be cast for {P} mana instead of colored mana. If life was paid, it enters with fewer loyalty counters.)",
	"double team": "Double team (When this creature attacks, if it’s not a token, conjure a duplicate into your hand. It loses double team.)",
	"echo": "Echo [Cost] (At the beginning of your upkeep, if you didn’t pay this card’s echo cost, sacrifice it.)",
	"enlist": "Enlist (As this creature attacks, you may tap a non-attacking creature you control without summoning sickness. Add its power to this creature’s until end of turn.)",
	"fear": "Fear (This creature can’t be blocked except by artifact creatures and/or black creatures.)",
	"for mirrodin!": "For Mirrodin! (When this Equipment enters the battlefield, create a 2/2 red Rebel creature token and attach it to it.)",
	"fortify": "Fortify [Cost] ([Cost]: Attach to target land you control. Fortify only as a sorcery.)",
	"frenzy": "Frenzy N (Whenever this creature attacks and isn’t blocked, it gets +N/+0 until end of turn.)",
	"fuse": "Fuse (You may cast one or both halves of this split card from your hand.)",
	"gravestorm": "Gravestorm (When you cast this spell, copy it for each permanent put into a graveyard this turn. You may choose new targets.)",
	"haunt": "Haunt (When this dies, exile it haunting target creature. When that creature dies, [effect].)",
	"hexproof from": "Hexproof from [Quality] (This permanent can’t be the target of [Quality] spells or abilities your opponents control.)",
	"improvise": "Improvise (Your artifacts can help cast this spell. Each artifact you tap pays for {1}.)",
	"ingest": "Ingest (Whenever this creature deals combat damage to a player, that player exiles the top card of their library.)",

	"islandcycling": "Islandcycling [Cost] ([Cost], Discard this card: Search your library for an Island card, reveal it, put it into your hand, then shuffle.)",
	"jump-start": "Jump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile it.)",
	"kicker": "Kicker [Cost] (You may pay an additional [cost] as you cast this spell. If you do, [effect].)",
	"kinship": "Kinship — At the beginning of your upkeep, you may look at the top card of your library. If it shares a creature type with this, you may reveal it. If you do, [effect].",
	"landwalk": "Landwalk (This creature can't be blocked as long as defending player controls a land with the specified land type.)",
	"legacy": "Legacy (A variant ability from Un-sets, often treated like a static or triggered ability.)",
	"legendary landwalk": "Legendary landwalk (Unblockable if defending player controls a legendary land.)",
	"lieutenant": "Lieutenant — As long as you control your commander, [effect].",
	"living metal": "Living metal (As long as it's your turn, this Vehicle is also a creature.)",
	"living weapon": "Living weapon (When this Equipment enters the battlefield, create a 0/0 black Germ creature token, then attach this to it.)",
	"melee": "Melee (Whenever this creature attacks, it gets +1/+1 until end of turn for each opponent you attacked this combat.)",
	"mobilize": "Mobilize N (Whenever this creature attacks, create N 1/1 red Warrior creature tokens tapped and attacking. Exile those tokens at the beginning of the next end step.)",
	"monstrosity": "Monstrosity N — [Cost] (If this creature isn’t monstrous, put N +1/+1 counters on it and it becomes monstrous.)",
	"more than meets the eye": "More Than Meets the Eye [Cost] (You may cast this card converted for its alternate form and cost.)",
	"mountaincycling": "Mountaincycling [Cost] ([Cost], Discard this card: Search your library for a Mountain card, put it into your hand, then shuffle.)",
	"mountainwalk": "Mountainwalk (Unblockable as long as defending player controls a Mountain.)",
	"multikicker": "Multikicker [Cost] (You may pay an additional [cost] any number of times as you cast this spell. [Effect per payment].)",
	"nightbound": "Nightbound (If a player cast no spells during their own turn, it becomes night next turn.)",
	"nonbasic landwalk": "Nonbasic landwalk (Unblockable if defending player controls a nonbasic land.)",
	"offering": "Offering — You may cast this spell as though it had flash by sacrificing a [type] and paying the difference in mana cost.",
	"offspring": "Offspring — When this creature dies, create a copy of it with lesser power and toughness. (Un-set ability.)",
	"parley": "Parley — Each player reveals the top card of their library. For each nonland revealed this way, [effect].",
	"plainscycling": "Plainscycling [Cost] ([Cost], Discard this card: Search your library for a Plains card, reveal it, put it into your hand, then shuffle.)",
	"plainswalk": "Plainswalk (Unblockable if defending player controls a Plains.)",
	"plot": "Plot [Cost] (You may pay [Cost] and exile this card. You may cast it on a later turn for free.)",
	"provoke": "Provoke (When this attacks, you may have target creature defending player controls untap and block it if able.)",
	"rally": "Rally — Whenever [subtype] enters the battlefield under your control, [effect].",
	"ravenous": "Ravenous (This creature enters the battlefield with X +1/+1 counters. If X is 5 or more, draw a card.)",
	"reinforce": "Reinforce N — [Cost] ([Cost], Discard this card: Put N +1/+1 counters on target creature.)",
	"retrace": "Retrace (You may cast this card from your graveyard by discarding a land card in addition to its other costs.)",
	"ripple": "Ripple N (When you cast this spell, you may reveal the top N cards of your library. You may cast any of them with the same name.)",
	"saddle": "Saddle [Cost] (You may tap a creature you control to help pay for this card’s saddle cost.)",
	"skulk": "Skulk (This creature can’t be blocked by creatures with greater power.)",
	"slivercycling": "Slivercycling [Cost] ([Cost], Discard this card: Search for a Sliver card, reveal it, put it into your hand, then shuffle.)",
	"specialize": "Specialize [Cost] ([Cost], Discard a card: Transform this card. Activate only as a sorcery.)",
	"spree": "Spree — You may pay additional costs for multiple effects as you cast this spell.",
	"squad": "Squad N (As an additional cost, you may pay [Cost] any number of times. Create N token copies of this spell.)",
	"spectacle": "Spectacle [Cost] (You may cast this card for its spectacle cost if an opponent lost life this turn.)",
	"sunburst": "Sunburst (This permanent enters the battlefield with a +1/+1 or charge counter for each color of mana spent to cast it.)",
	"surge": "Surge [Cost] (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)",
	"suspect": "Suspect (Mark a creature as suspect. It can’t block while suspected.)",
	"sweep": "Sweep — Return any number of [type]s you control to their owner’s hand. [Effect per card returned.]",
	"transform": "Transform (Turn a double-faced card to its other side. This action is often linked to triggers or conditions.)",
	"treasure": "Treasure — Artifact tokens with 'T, Sacrifice this artifact: Add one mana of any color.'",
	"typecycling": "Typecycling [Cost] ([Cost], Discard this card: Search your library for a card with the given type, reveal it, put it into your hand, then shuffle.)",
	"umbra armor": "Umbra armor — Totem armor variant, often grants totem armor and other boosts.",
	"undaunted": "Undaunted (This spell costs {1} less to cast for each opponent.)",
	"underdog": "Underdog — If you have less life than an opponent, [effect].",
	"unearth": "Unearth [Cost] ([Cost]: Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield.)",
	"void": "Void — If a nonland permanent left the battlefield this turn or a spell was warped this turn, [effect].",
	"doctor's companion": "Doctor's companion — If your starting deck includes The Doctor, you may have two commanders if one has doctor’s companion.",
	"double": "Double — When this permanent enters, double a certain stat, value, or count. (Appears on specific cards with alternate effects.)",
	"heist": "Heist — If you attacked this turn, exile the top card of your library. You may play it this turn.",
	"forage": "Forage — Choose up to X cards in graveyards, then shuffle them into their owners’ libraries.",
	"freerunning": "Freerunning — When you cast this spell after attacking with a creature, [effect]. (Appears in Universes Beyond.)",
	"gift": "Gift — This permanent enters with an additional bonus or shared effect with another card. (e.g., Gift of Compleation.)",
	"harmonize": "Harmonize — When this creature enters or dies, another permanent gains a bonus or triggers an additional ability. (Flavorful tag.)",
	"exhaust": "Exhaust — After activation, this permanent can’t be untapped for a set number of turns or until a condition is met.",
	"max speed": "Max Speed — Used in Un-sets to denote haste + evasion. (Not a rules-meaningful term in black-bordered sets.)",
	"start your engines!": "Start your engines! — If you control a Vehicle, [effect].",
	"adapt": "Adapt N — [Cost]: If this creature has no +1/+1 counters on it, put N +1/+1 counters on it.",
	"basic landcycling": "Basic landcycling [Cost] — Discard this card: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.",
	"casualty": "Casualty N — As you cast this spell, you may sacrifice a creature with power N. If you do, it triggers an additional effect.",
	"channel": "Channel — [Cost], Discard this card: [Effect]. Activate only as a sorcery.",
	"chroma": "Chroma — Effect is based on count of colored mana symbols among permanents you control.",
	"converge": "Converge — Effect is based on number of colors of mana spent to cast this spell.",

	"desertwalk": "Desertwalk — This creature can’t be blocked as long as defending player controls a Desert.",
	"dethrone": "Dethrone — Whenever this creature attacks the player with the greatest life total (or tied), put a +1/+1 counter on it.",
	"devoid": "Devoid — This card is colorless, regardless of its mana cost.",
	"eminence": "Eminence — While this is on the battlefield, if it’s not on the battlefield, you get an effect as long as you control it.",
	"encore": "Encore [Cost] (Exile this card from your graveyard. For each opponent, create a token copy that attacks that opponent this turn if able. Sacrifice them at end of combat. Activate only as a sorcery.)",
	"evolve": "Evolve — When a creature with greater power or toughness enters under your control, put a +1/+1 counter on this creature.",
	"exalted": "Exalted — Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
	"explore": "Explore — Reveal the top card of your library. If it’s a land card, put it onto the battlefield tapped. Otherwise, put it into your hand.",
	"forestcycling": "Forestcycling [Cost] — Discard this card: Search library for a Forest, put it into your hand.",
	"forestwalk": "Forestwalk — This creature can’t be blocked as long as defending player controls a Forest.",
	"hellbent": "Hellbent — Effect is active if you have no cards in hand.",
	"imprint": "Imprint — Exile a card to grant abilities to a permanent as long as it remains exiled.",
	"islandwalk": "Islandwalk — This creature can’t be blocked as long as defending player controls an Island.",
	"join forces": "Join forces — Players in turn order may pay any amount of mana; total mana increases effect symmetrically.",
	"landcycling": "Landcycling [Cost] — Discard this card: Search library for a land card, put it into your hand.",
	"radiance": "Radiance — Target something, effect applies to all permanents of same type that share a color with that target.",
	"strive": "Strive — You may pay extra as you cast this spell to target additional targets.",
	"support": "Support — Put +1/+1 counter on target creature and/or another creature.",
	"swampcycling": "Swampcycling [Cost] — Discard this card: Search library for a Swamp, put it into your hand.",
	"swampwalk": "Swampwalk — This creature can’t be blocked as long as defending player controls a Swamp.",
	"vote": "Vote — Players choose among options; result based on majority, sometimes with multiple votes allowed.",
	"manifest": "Manifest (Put a card from your library onto the battlefield face down as a 2/2 creature. It can be turned face up if it’s a creature card.)",
	"manifest dread": "Manifest dread — Look at the top two cards of your library. Manifest one face down as a 2/2 creature and put the other into your graveyard.",
	"warp": "Warp — You may cast this spell for its warp cost; it enters the battlefield. At the beginning of the next end step, exile it. You may later cast it from exile for its mana cost.",
	"station": "Station — [Ability] Tap an untapped creature you control: Put charge counters equal to that creature’s power on this permanent. Activate only as a sorcery. At a specified number, this permanent becomes a creature with abilities.",

	# arena only keywords
	"perpetual": "Perpetual (Effects with this keyword apply permanently, even across zone changes.)",
	"spellbook": "Spellbook (When triggered, you may choose one of several predefined cards to conjure into your hand.)",
	"intensity": "Intensity — [Rule] where this spell or permanent becomes stronger the higher its intensity.",
}

keywordActions ={
	"cast": "To cast a spell, you put it on the stack, choose modes, targets, and pay its mana and additional costs. It then resolves or gets countered.",
	"counter": "To counter a spell or ability is to cancel it before it resolves. A countered spell goes to the graveyard.",
	"create": "To create a token is to put it onto the battlefield. Tokens can be creatures, treasures, clues, food, etc.",
	"destroy": "To destroy a permanent is to put it into its owner’s graveyard. Indestructible permanents cannot be destroyed.",
	"discard": "To discard a card is to put it from your hand into your graveyard. Some effects require discarding as a cost or effect.",
	"exile": "To exile a card is to put it outside the game. It stays exiled unless another effect brings it back.",
	"play": "To play a land or cast a spell is to put it into action. Playing a land doesn’t use the stack.",
	"regenerate": "To regenerate is to prevent a creature from dying. The next time it would be destroyed, it taps and is removed from combat instead.",
	"reveal": "To reveal a card is to show it to all players, usually from your hand or the top of your library.",
	"sacrifice": "To sacrifice a permanent is to put it into its owner's graveyard. Sacrificing can’t be prevented.",
	"shuffle": "To shuffle means to randomize the order of cards in a library or other zone. Often done after searches.",
	"tap": "To tap a card is to turn it sideways to indicate it’s been used. Commonly used for mana or attacking.",
	"untap": "To untap is to rotate a tapped card back to its upright position. Happens during the untap step or via effects.",

	"surveil": "Surveil N (Look at the top N cards of your library, then put any number into your graveyard and the rest back on top in any order.)",
	"connive": "Connive (Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.)",
	"venture into the dungeon": "Venture into the dungeon (Enter the first room of a dungeon or advance to the next room if already inside one.)",
	"exert": "Exert (When you exert a creature, it won’t untap during your next untap step. In exchange, it usually gets a bonus.)",
	"investigate": "Investigate (Create a colorless Clue artifact token with '2, Sacrifice this: Draw a card.')",
	"proliferate": "Proliferate (Choose any number of permanents and/or players with counters, then give each another of those counters.)",
	"mill": "Mill N (Put the top N cards of a player’s library into their graveyard.)",
	"learn": "Learn (You may reveal a Lesson card from outside the game and put it into your hand, or discard a card to draw a card.)",

	"scry": "Scry N (Look at the top N cards of your library. Put any number on the bottom and the rest on top in any order.)",
	"populate": "Populate (Create a token that’s a copy of a creature token you control.)",
	"detain": "Detain (Until your next turn, target nonland permanent an opponent controls can’t attack, block, or activate its abilities.)",
	"amass": "Amass N (Put N +1/+1 counters on an Army you control. If you don’t control one, create a 0/0 black Army creature token first.)",
	"incubate": "Incubate N (Create an Incubator token with N +1/+1 counters. You may transform it later into a 0/0 Phyrexian artifact creature.)",
	"clash": "Clash (Each clashing player reveals the top card of their library, then puts it on top or bottom. Higher mana value wins the clash.)",
	"fateseal": "Fateseal N (Look at the top N cards of an opponent’s library. You may put any number of them on the bottom and the rest on top in any order.)",
	"planeswalk": "Planeswalk (Move to a new plane card. Triggers planechase abilities.)",
	"time travel": "Time travel (Un-set only: advance or rewind turns. For silver-border formats only.)",

	"set in motion": "Set in motion (Start a phenomenon card’s effect at the beginning of a Planechase game.)",
	"abandon": "Abandon (Move away from the current plane card without triggering a planeswalk effect.)",
	"assemble": "Assemble (Put a Contraption card into one of your sprockets.)",
	"bolster": "Bolster N (Choose a creature you control with the least toughness and put N +1/+1 counters on it.)",
	"cloak": "Cloak (To cloak a card is to put it onto the battlefield face down as a 2/2 creature with ward {2}. It can be turned face up if it's a creature card.)",
	"convert": "Convert (Transform this double-faced card.)",
	"forage": "Forage (Choose up to X cards in graveyards, then shuffle them into their owners’ libraries.)",
	"heist": "Heist (Exile the top card of your library. You may play that card this turn if you attacked this turn.)",
	"open an attraction": "Open an Attraction (Reveal cards from your attraction deck until you reveal one that isn’t already open. Put it onto the battlefield.)",
	"roll to visit your attractions": "Roll to visit your Attractions (At the beginning of your main phase, roll a six-sided die to see which attractions you visit.)",
	"activate": "Activate — See rule 601.2: Pay costs to activate an activated ability; put it on the stack.",
	"attach": "Attach — The action of putting an Aura or Equipment onto a permanent.",
	"exchange": "Exchange — Swap control or characteristics of two permanent or cards as instructed.",
	"fight": "Fight — Two target creatures deal damage equal to their power to each other.",
	"food": "Food — Artifact tokens with 'T, Sacrifice this artifact: You gain 3 life.'",
	"collect evidence": "Collect evidence — Arena-specific: Create a Clue token.",
	"discover": "Discover — Arena-specific: Reveal cards until you find a nonland, then put it into your hand.",
	"demonstrate": "(설명 없음) – 모르는 항목입니다.",

	"goad": "Goad — Until your next turn, this creature attacks each combat if able and attacks a player other than you if able.",

	# arena only keywords
	"seek": "Seek (Arena-only): Randomly select a card in your library that matches certain criteria. You don't shuffle afterward.",
	"conjure": "Conjure (Arena-only): Create a copy of a specific card and put it into your hand, graveyard, or library.)",
	"materialize": "Materialize (Arena-only): Exile a card, then create a token copy of it."
}

abilityWords = {
	"landfall": "Landfall — Whenever a land enters the battlefield under your control, [effect].",
	"delirium": "Delirium — If there are four or more card types among cards in your graveyard, [effect].",
	"raid": "Raid — If you attacked with a creature this turn, [effect].",
	"morbid": "Morbid — If a creature died this turn, [effect].",
	"metalcraft": "Metalcraft — If you control three or more artifacts, [effect].",
	"spell mastery": "Spell mastery — If there are two or more instant or sorcery cards in your graveyard, [effect].",
	"ferocious": "Ferocious — If you control a creature with power 4 or greater, [effect].",
	"formidable": "Formidable — If creatures you control have total power 8 or greater, [effect].",
	"fateful hour": "Fateful hour — If you have 5 or less life, [effect].",
	"domain": "Domain — Effect based on number of basic land types among lands you control.",
	"constellation": "Constellation — Whenever an enchantment enters the battlefield under your control, [effect].",
	"heroic": "Heroic — Whenever you cast a spell that targets this creature, [effect].",
	"threshold": "Threshold — As long as seven or more cards are in your graveyard, [effect].",
	"battalion": "Battalion — Whenever this and at least two other creatures attack, [effect].",
	"undergrowth": "Undergrowth — Effect based on number of creature cards in your graveyard.",
	"magecraft": "Magecraft — Whenever you cast or copy an instant or sorcery spell, [effect].",
	"pack tactics": "Pack tactics — If you attack with creatures with total power 6 or greater, [effect].",
	"coven": "Coven — If you control three or more creatures with different powers, [effect].",
	"adamant": "Adamant — If at least three mana of the same color was spent to cast this spell, [effect].",
	"alliance": "Alliance — Whenever another creature enters the battlefield under your control, [effect].",
	"celebration": "Celebration — If two or more nonland permanents entered the battlefield under your control this turn, [effect].",
	"descend": "Descend — If a permanent card was put into your graveyard this turn, [effect].",
	"fathomless descent": "Fathomless Descent — Effects based on the number of permanent cards in your graveyard.",
	"corrupted": "Corrupted — If an opponent has three or more poison counters, [effect].",
	"valiant": "Valiant — If a creature you control with the highest power dies this turn, [effect].",
	"survival": "Survival — If you control no other creatures, [effect].",
	"flurry": "Flurry — If you've cast two or more spells this turn, [effect].",
	"paradox": "Paradox — If you cast a spell from anywhere other than your hand this turn, [effect].",
	"enrage": "Enrage — Whenever this creature is dealt damage, [effect].",
	"will of the planeswalkers": "Will of the Planeswalkers — Starting with you, each player votes for chaos or stability. Then effects happen based on the majority vote.",
	"secret council": "Secret council — Players vote in secret, then reveal simultaneously. Effects trigger based on vote outcomes.",

	"addendum": "Addendum — If you cast this spell during your main phase, it gains an additional effect.",
	"choose a background": "Choose a background — You select a Background enchantment to pair with a partner creature.",
	"daybound": "Daybound — If a player casts no spells during their own turn, the day becomes night; transforms related cards.",
	"impending": "Impending N — [cost]: This permanent enters with N time counters and isn't a creature until the last is removed. At the beginning of your end step, remove a time counter.",
	"revolt": "Revolt — If a permanent you controlled left the battlefield this turn, [effect].",
	"teamwork": "Teamwork — Whenever this creature and another attack together, [effect].",
	"tempting offer": "Tempting offer — When you cast this spell, each opponent may copy it and choose a target. For each one who does, [bonus effect].",
	"will of the council": "Will of the Council — Players vote for options; the majority determines the outcome, but minority options may still trigger.",

	"council's dilemma": "Council's dilemma — When this enters, players vote for options; effects resolve based on votes.",
	"grandeur": "Grandeur — Discard another card with the same name: [effect].",

	# role tokens
	"role token": "Roles are colorless Aura enchantment tokens with 'Enchant creature'. Only one Role per creature per player can be attached at a time. If another Role is created for the same creature by the same player, the old Role is put into the graveyard.",
	"cursed": "Cursed — Enchanted creature has base power and toughness 1/1. {{ROLE}}",
	"monster": "Monster — Enchanted creature gets +1/+1 and has trample. {{ROLE}}",
	"royal": "Royal — Enchanted creature gets +1/+1 and has ward {1}. {{ROLE}}",
	"sorcerer": "Sorcerer — Enchanted creature gets +1/+1 and has 'Whenever this creature attacks, scry 1.' {{ROLE}}",
	"wicked": "Wicked — Enchanted creature gets +1/+1. When this Aura is put into a graveyard from the battlefield, each opponent loses 1 life. {{ROLE}}",
	"young hero": "Young Hero — Enchanted creature has 'Whenever this creature attacks, if its toughness is 3 or less, put a +1/+1 counter on it.' {{ROLE}}",
	"virtuous": "Virtuous — Enchanted creature gets +1/+1 for each enchantment you control. {{ROLE}}",
	"chef": "Chef — Enchanted creature gets +1/+1 and has 'Whenever this creature attacks, create a Food token.' {{ROLE}}",
	"huntsman": "Huntsman — Enchanted creature gets +1/+1 and has '{T}: Add {G}.' {{ROLE}}",
	"questing": "Questing — Enchanted creature has all abilities of Questing Beast. {{ROLE}}",
}

specialWords = {
	"adventure": "Adventure is a special card type that allows you to cast a spell as an instant or sorcery before casting the creature part. The adventure card is exiled after casting the adventure part.",
	"gold": "Gold is an artifact token with 'Sacrifice this artifact: Add one mana of any color.'",
	"treasure": "Treasure is an artifact token with 'T, Sacrifice this artifact: Add one mana of any color.'",
	"clue": "Clue is an artifact token with '2, Sacrifice this artifact: Draw a card.'",
	"food": "Food is an artifact token with '2, T, Sacrifice this artifact: You gain 3 life.'",
	"blood": "Blood is an artifact token with '1, T, Discard a card, Sacrifice this artifact: Draw a card.'",
	"incubator": "Incubator is a token with a number of +1/+1 counters on it. You may pay {2} to transform it into a 0/0 Phyrexian artifact creature.",
	"map": "Map is an artifact token with '1, T, Sacrifice this artifact: Target creature you control explores. Activate only as a sorcery.' Explore means that creature’s controller reveals the top card of their library. If it's a land card, put it into their hand. Otherwise, put a +1/+1 counter on that creature and you may put the card into the graveyard.",
	"lander": "Lander is an artifact token with {2}, {T}, Sacrifice this token: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.",
	"monarch": "Monarch is a designation a player can have. At the beginning of your end step, if you're the monarch, you draw a card. A player becomes the monarch by dealing combat damage to the current monarch.",
    "role": "Roles are colorless Aura enchantment tokens with 'Enchant creature'. Only one Role per creature per player can be attached at a time. If another Role is created for the same creature by the same player, the old Role is put into the graveyard.",
    "initiative": "The Initiative is a designation a player can have. When you take the Initiative, you venture into the Undercity. If you already have the Initiative, you instead venture deeper. The Initiative can be stolen by dealing combat damage to the player who currently has it.",
    "city_blessing": "The City's Blessing is a status you gain once you control ten or more permanents. Once you have it, you keep it for the rest of the game. Some cards have Ascend and become stronger if you have the City’s Blessing.",
    "party": "A party consists of up to one each of Cleric, Rogue, Warrior, and Wizard you control. Some cards become stronger depending on how many unique roles are filled in your party."
}

specialCounters = {
	"finality": "Finality Counter — If a permanent with a finality counter would die, exile it instead.",
	"shield": "Shield Counter — If this permanent would be destroyed or dealt damage, remove a shield counter instead.",
	"stun": "Stun Counter — If a permanent with a stun counter would untap, remove one instead.",
}
